### ISSUE TITLE
NotFoundError: Tensor name "FPN/Conv/BatchNorm/beta/ExponentialMovingAverage" not found in checkpoint files resnet_v1_50.ckp

### ISSUE THREAD

**Issue by aligoglos** [AirBernard/Scene-Text-Detection-with-SPCNET#3]
i tried to run demo.py but this error occurred :
```
C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:tensorflow:From D:\Artificial Intelligence\OCR\Source\_TextDetection\Scene-Text-Detection-with-SPCNET-master\Scene-Text-Detection-with-SPCNET-master\nets\resnet_v1.py:198: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From demo.py:71: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
2019-05-18 15:44:11.831124: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-05-18 15:44:12.404659: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1405] Found device 0 with properties:
name: GeForce GTX 960M major: 5 minor: 0 memoryClockRate(GHz): 1.176
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.34GiB
2019-05-18 15:44:12.417219: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1484] Adding visible gpu devices: 0
2019-05-18 15:44:13.382238: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-18 15:44:13.387809: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971]      0
2019-05-18 15:44:13.391664: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:984] 0:   N
2019-05-18 15:44:13.397247: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3065 MB memory) -> physical GPU (device: 0, name: GeForce GTX 960M, pci bus id: 0000:01:00.0, compute capability: 5.0)
Restore from models/pretrained_models/resnet_v1_50.ckpt
Traceback (most recent call last):
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1278, in _do_call
    return fn(*args)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "FPN/Conv/BatchNorm/beta/ExponentialMovingAverage" not found in checkpoint files models/pretrained_models/resnet_v1_50.ckpt
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
         [[Node: save/RestoreV2/_65 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_84_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
```

**Comment by yanxu1per** [comment]
same error here...

**Comment by ujjawalcse** [comment]
Have you got any solution @aligoglos?

**Comment by pravendrakhichi** [comment]
@ujjawalcse The problem is with checkpoint  usually when save a model it create meta, data and ckpt file but the checkpoint u r providing here doesn't contain information about latest checkpoint hence you are not able to restore from the checkpoint.

**Comment by ujjawalcse** [comment]
Ohk Sir. Thanks.

**Comment by p971030** [comment]
> @ujjawalcse The problem is with checkpoint usually when save a model it create meta, data and ckpt file but the checkpoint u r providing here doesn't contain information about latest checkpoint hence you are not able to restore from the checkpoint.

So how to solve the problem?

**Comment by p971030** [comment]
@ujjawalcse  How to solve the problem if the provided  checkpoint contains no information about latest checkpoint?

**Comment by p971030** [comment]
@ujjawalcse  How to solve the problem if the provided  checkpoint contains no information about latest checkpoint?
